trigger:
  branches:
    include:
      - main  # branch name

pool:
  name: Default

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Python version
      addToPath: true

  - script: |
      python3 jokes.py
    displayName: 'Run Flask app'
